### ISSUE TITLE
[FATAL tini (6)] exec /bin/entry.sh failed: No such file or directory

### ISSUE THREAD

**Issue by sgofferj** [home-assistant/docker#107] opened 2020-03-21 22:10 UTC
Just pulled the latest stable image: sha256:c836c31c0b797d5818ccd6fd8dd3ee512cf3526eeb95ca65f80a0193b20e9fb8 and it won't come up. Just seeing
[FATAL tini (6)] exec /bin/entry.sh failed: No such file or directory
repeating in the container output.

**Comment by frenck** [comment] 2020-03-22 11:37
This is most likely caused by overriding the CMD in your docker settings.
One should not override that, unless you have a good reason to.

In this release our internal CMD has been replaced by a entry point that starts a init. So probably just removing the CMD from your settings will fix it.

**Comment by mazhead** [comment] 2020-03-22 17:51
@frenck 
Have the same issue on the latest stable.
Using stock compose:

```
version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - homeassistant:/config
    environment:
      - TZ=Europe/Prague
    restart: always
    network_mode: host

volumes:
  homeassistant:
```

In this commit the ENTRYPOINT has been removed: https://github.com/home-assistant/docker/commit/f0bef9e9cc1a6ef51b238a75fc0208c3393a2e0c#diff-de2dfe904ac98a74495473e67a0d0e2c

Even if you move to S6 overlay you need to have a ENTRYPOINT pointing to init:
https://github.com/just-containers/s6-overlay/wiki#usage

**Comment by mazhead** [comment] 2020-03-22 18:00
Just to confirm, the previous version does not have this issue.
So anyone facing this issue right now with "stable" release just revert to the last "stable" release which was: 0.107.4.

E.g. change the image line in your compose to:
` image:  homeassistant/home-assistant:0.107.4`

After it has been fixed you can move back to the stable.

**Comment by mazhead** [comment] 2020-03-22 18:47
I have just pulled: sha256:92bf2b20b76dab912b599bf6a7037a5f7fdcc620994dc5db0057e7f1da774b19
and it seems to be working again.

🤷‍♂

**Comment by DominikPalo** [comment] 2020-03-22 18:51
I have the same issue with the latest version - I used to update HA using the "Recreate container" with "Pull latest image" functionality in Portainer, which was working before without issues, but now it fails with error: 
![image](https://user-images.githubusercontent.com/1623257/77257728-7bf7ce80-6c76-11ea-8607-344af4e98b2e.png)

**Comment by mazhead** [comment] 2020-03-22 19:04
@DominikPalo -> I was upgrading via https://github.com/pyouroboros/ouroboros but the concept is same as in portainer with recreate + pull latest.
 
Since they removed the ENTRYPOINT inside the Dockerfile and are using the ENTRYPOINT from the BASE image I think the process of "upgrade" got confused.

What I did was change the image to 0.107.4 (see above) and after that I pulled the latest stable again (remove the old one) and again change it to stable. 

There is nothing wrong what they did in the code, seems to be a docker problem itself.

**Comment by frenck** [comment] 2020-03-22 19:45
@mazhead Thank for the education on S6, however, a bit unneeded. I've been using S6 for over 2,5 years now and maintain 335 public Docker images that are all using S6 as well.

The entry point is here: <https://github.com/home-assistant/docker-base/blob/master/alpine/amd64/Dockerfile#L36>

It doesn't matter in which layer the entry point is set. The last that sets it remains used.

The problem is generally caused by overriding the CMD or entry point by the user or the management software used. For example, Portainer is a known problems, since it does not adopt these settings @ later stages (which, according to many, is wrong).

That said, if you use the Home Assistant directly, without messing around with inits, entrypoints or cmd's, it will just work as advertised.

**Comment by frenck** [comment] 2020-03-22 19:48
@DominikPalo In Portainer clear the CMD field of your container. Portainer should not mess with that. After that is will just start.

**Comment by mazhead** [comment] 2020-03-22 19:50
@frenck I did not mean to be negative with the S6, I did not see the relation between the base image at first glance. 
Thank you for clearing it up. 
I personally did not use a management software, pure compose as mentioned above and using ourobourous to upgrade. If that is causing similar cases as portainer then it is unfortunate and will check their repo how they actually do it. 

Again thanks for inputs.

**Comment by DominikPalo** [comment] 2020-03-22 19:58
@frenck thank you, I tried deleting the `Command = 'python' '-m' 'homeassistant' '--config' '/config'` from the Portainer config, but it didn't help (it was still saying `/bin/entry.sh` doesn't exist). So then I tried to delete also the `Entry Point = /bin/entry.sh` and now Portainer doesn't allow me to deploy the container - it says: "Failure: No command specified"
![image](https://user-images.githubusercontent.com/1623257/77259132-b3b74400-6c7f-11ea-81a7-8fc5bbd34823.png)
![image](https://user-images.githubusercontent.com/1623257/77259136-bade5200-6c7f-11ea-8d6d-d5a5d638b270.png)

**Comment by DominikPalo** [comment] 2020-03-22 20:01
But, I've just deleted the old container and deployed a fresh new one using a command: `docker run --init -d --name="home-assistant" -e "TZ=Europe/Bratislava" -v /srv/homeautomation/hass-config:/config --net=host homeassistant/home-assistant:stable` and everything work ok, I'm finally on version 107.5. :)

But it's a bit strange that it is not possible to do it using the Portaner web interface.

**Comment by mazhead** [comment] 2020-03-22 20:08
Anyone stumbling on this issue in the future:
1. If you use portainer for upgrades, follow this issue: https://github.com/portainer/portainer/issues/3604
2. If you use ouroboros for upgrades, follow this issue: https://github.com/pyouroboros/ouroboros/issues/337

Thank you again @frenck for your inputs.

**Comment by sgofferj** [comment] 2020-03-23 09:43
I can confirm that clearing the "entrypoint" field in Portainer (duplicate/edit container) is a viable workaround.

**Comment by pvizeli** [comment] 2020-03-25 14:02
I think the problem is fixed now. I close this PR 👍

**Closed by pvizeli** 2020-03-25 14:02 UTC
